[package]
name = "mmse"
version = "0.1.0"
authors = ["Yishen Miao <mys721tx@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"

[dependencies.lz4]
git = "https://github.com/bozaro/lz4-rs.git"
rev = "6de7f00"
